export type Job = {
  id: number;
  title: string;
  location: string;
  type: string;
  slug: string;
  minSalary: number;
  maxSalary: number;
  deadline: string;
  categories: string[];
  description?: string;
  requirements?: string[];
  bonusSkills?: string[];
  benefits?: string[];
};

// Raw careers data without translations - used for generateStaticParams
const RAW_CAREERS: Job[] = [
  {
    id: 1,
    title: "Enterprise SEO Consultant",
    location: "Cairo, Egypt",
    type: "Full Time",
    slug: "enterprise-seo-consultant",
    minSalary: 6000,
    maxSalary: 13000,
    deadline: "January 1, 2026",
    categories: ["cat1", "cat3", "cat5"],
    description:
      "We are looking for an experienced SEO consultant to help our clients improve their search engine rankings and online visibility.",
    requirements: [
      "5+ years of SEO experience",
      "Deep knowledge of Google Search Console and Analytics",
      "Experience with technical SEO audits",
      "Proficiency in keyword research tools",
      "Strong analytical and reporting skills",
      "Experience with content optimization",
      "Understanding of link building strategies",
      "Familiarity with mobile SEO",
      "English and Arabic fluency preferred",
    ],
    bonusSkills: [
      "Experience with PPC campaigns",
      "Knowledge of local SEO",
      "International SEO expertise",
      "Experience with Screaming Frog and SEMrush",
      "Basic HTML and CSS knowledge",
      "Experience with WordPress and Shopify",
    ],
    benefits: [
      "Competitive salary based on experience",
      "Health insurance coverage",
      "Professional development budget",
      "Remote work flexibility",
      "Quarterly performance bonuses",
    ],
  },
  {
    id: 2,
    title: "IT Infrastructure Manager",
    location: "Cairo, Egypt",
    type: "Full Time",
    slug: "it-infrastructure-manager",
    minSalary: 6000,
    maxSalary: 13000,
    deadline: "October 10, 2027",
    categories: ["cat2", "cat4"],
    description:
      "Manage and maintain our IT infrastructure, ensuring optimal performance, security, and reliability of all systems and networks.",
    requirements: [
      "7+ years of IT infrastructure management experience",
      "Strong knowledge of Windows and Linux systems",
      "Experience with cloud platforms (AWS, Azure, GCP)",
      "Network administration and security expertise",
      "Database management skills",
      "Experience with virtualization technologies",
      "Knowledge of IT service management (ITIL)",
      "Strong problem-solving abilities",
      "Excellent communication skills",
    ],
    bonusSkills: [
      "Kubernetes and containerization experience",
      "CI/CD pipeline management",
      "Infrastructure as Code (Terraform, Ansible)",
      "Disaster recovery planning",
      "Cybersecurity certifications",
      "Experience with monitoring tools",
    ],
    benefits: [
      "Excellent salary package",
      "Comprehensive health insurance",
      "Annual training and certification allowance",
      "Flexible working arrangements",
      "Performance incentives",
    ],
  },
  {
    id: 3,
    title: "Technical Project Manager",
    location: "Cairo, Egypt",
    type: "Full Time",
    slug: "technical-project-manager",
    minSalary: 6000,
    maxSalary: 13000,
    deadline: "April 10, 2028",
    categories: ["cat1", "cat5"],
    description:
      "Lead technical projects from conception to delivery, ensuring timely completion, quality standards, and stakeholder satisfaction.",
    requirements: [
      "5+ years of project management experience",
      "Technical background in software development",
      "Strong knowledge of Agile and Scrum methodologies",
      "Experience with project management tools (Jira, Asana)",
      "Excellent communication and leadership skills",
      "Risk management expertise",
      "Budget management experience",
      "Stakeholder management skills",
      "Problem-solving and decision-making abilities",
    ],
    bonusSkills: [
      "PMP or PRINCE2 certification",
      "Experience with DevOps processes",
      "Knowledge of software testing methodologies",
      "Experience with AI/ML projects",
      "Business analysis skills",
      "Six Sigma certification",
    ],
    benefits: [
      "Competitive salary",
      "Health and wellness benefits",
      "Professional certification support",
      "Remote work options",
      "Annual bonus structure",
    ],
  },
  {
    id: 4,
    title: "Cloud Solutions Architect",
    location: "Cairo, Egypt",
    type: "Full Time",
    slug: "cloud-solutions-architect",
    minSalary: 6000,
    maxSalary: 13000,
    deadline: "May 10, 2026",
    categories: ["cat2", "cat3"],
    description:
      "Design and implement scalable cloud solutions for enterprise clients, ensuring security, performance, and cost optimization.",
    requirements: [
      "7+ years of cloud architecture experience",
      "Expert-level knowledge of AWS, Azure, or GCP",
      "Strong understanding of cloud security and compliance",
      "Experience with microservices architecture",
      "Knowledge of containerization and orchestration",
      "Experience with cloud databases",
      "Cost optimization expertise",
      "Strong technical communication skills",
      "Experience with enterprise solutions",
    ],
    bonusSkills: [
      "AWS Solutions Architect certification",
      "Kubernetes expertise",
      "Infrastructure as Code proficiency",
      "Machine learning and AI knowledge",
      "Serverless architecture experience",
      "Multi-cloud expertise",
    ],
    benefits: [
      "High-end salary package",
      "Comprehensive benefits",
      "Training and certification budget",
      "Flexible work arrangements",
      "Performance bonuses",
    ],
  },
  {
    id: 5,
    title: "IT Support Engineer",
    location: "Cairo, Egypt",
    type: "Full Time",
    slug: "it-support-engineer",
    minSalary: 6000,
    maxSalary: 13000,
    deadline: "December 6, 2026",
    categories: ["cat1", "cat4"],
    description:
      "Provide technical support to end-users, troubleshoot issues, and maintain IT systems to ensure business continuity.",
    requirements: [
      "2+ years of IT support experience",
      "Proficiency in Windows and macOS environments",
      "Knowledge of networking basics",
      "Experience with ticketing systems",
      "Strong troubleshooting skills",
      "Customer service excellence",
      "Hardware and software troubleshooting",
      "Basic scripting knowledge",
      "English and Arabic communication skills",
    ],
    bonusSkills: [
      "Linux administration",
      "Python or PowerShell scripting",
      "Cloud service knowledge",
      "ITIL certification",
      "Active Directory experience",
      "VPN and security tools knowledge",
    ],
    benefits: [
      "Competitive salary",
      "Health insurance",
      "Paid time off",
      "Remote work options",
      "Career development opportunities",
    ],
  },
  {
    id: 6,
    title: "Global Benefits Manager",
    location: "Cairo, Egypt",
    type: "Full Time",
    slug: "global-benefits-manager",
    minSalary: 6000,
    maxSalary: 13000,
    deadline: "December 10, 2024",
    categories: ["cat2", "cat3", "cat5"],
    description:
      "Manage global employee benefits programs, ensuring compliance, cost-effectiveness, and employee satisfaction across multiple regions.",
    requirements: [
      "5+ years of benefits management experience",
      "Knowledge of international HR regulations",
      "Experience with benefits administration platforms",
      "Understanding of health insurance and pension plans",
      "Strong analytical and negotiation skills",
      "Experience with multi-country benefits programs",
      "Excellent communication skills",
      "Project management abilities",
      "Knowledge of compliance and regulations",
    ],
    bonusSkills: [
      "HRCI certification",
      "Experience with wellness programs",
      "Risk management knowledge",
      "Data analysis expertise",
      "Experience with payroll systems",
      "Knowledge of employee relations",
    ],
    benefits: [
      "Excellent salary",
      "Comprehensive benefits package",
      "Professional development support",
      "Flexible working hours",
      "Performance bonuses",
    ],
  },
];

// Get raw careers without translations (for static generation)
export const getRawCareers = (): Job[] => RAW_CAREERS;

// Get careers with translations (for rendering)
const getCareers = (t: any): Job[] => [
  {
    ...RAW_CAREERS[0],
    title: t("j1Title"),
    location: t("j1Location"),
    type: t("fullTime"),
    description: t("j1Desc"),
    requirements: [
      t("j1Req1"),
      t("j1Req2"),
      t("j1Req3"),
      t("j1Req4"),
      t("j1Req5"),
      t("j1Req6"),
      t("j1Req7"),
      t("j1Req8"),
      t("j1Req9"),
    ],
    bonusSkills: [
      t("j1Bonus1"),
      t("j1Bonus2"),
      t("j1Bonus3"),
      t("j1Bonus4"),
      t("j1Bonus5"),
      t("j1Bonus6"),
    ],
    benefits: [
      t("j1Benefit1"),
      t("j1Benefit2"),
      t("j1Benefit3"),
      t("j1Benefit4"),
      t("j1Benefit5"),
    ],
  },
  {
    ...RAW_CAREERS[1],
    title: t("j2Title"),
    location: t("j2Location"),
    type: t("fullTime"),
    description: t("j2Desc"),
    requirements: [
      t("j2Req1"),
      t("j2Req2"),
      t("j2Req3"),
      t("j2Req4"),
      t("j2Req5"),
      t("j2Req6"),
      t("j2Req7"),
      t("j2Req8"),
      t("j2Req9"),
    ],
    bonusSkills: [
      t("j2Bonus1"),
      t("j2Bonus2"),
      t("j2Bonus3"),
      t("j2Bonus4"),
      t("j2Bonus5"),
      t("j2Bonus6"),
    ],
    benefits: [
      t("j2Benefit1"),
      t("j2Benefit2"),
      t("j2Benefit3"),
      t("j2Benefit4"),
      t("j2Benefit5"),
    ],
  },
  {
    ...RAW_CAREERS[2],
    title: t("j3Title"),
    location: t("j3Location"),
    type: t("fullTime"),
    description: t("j3Desc"),
    requirements: [
      t("j3Req1"),
      t("j3Req2"),
      t("j3Req3"),
      t("j3Req4"),
      t("j3Req5"),
      t("j3Req6"),
      t("j3Req7"),
      t("j3Req8"),
      t("j3Req9"),
    ],
    bonusSkills: [
      t("j3Bonus1"),
      t("j3Bonus2"),
      t("j3Bonus3"),
      t("j3Bonus4"),
      t("j3Bonus5"),
      t("j3Bonus6"),
    ],
    benefits: [
      t("j3Benefit1"),
      t("j3Benefit2"),
      t("j3Benefit3"),
      t("j3Benefit4"),
      t("j3Benefit5"),
    ],
  },
  {
    ...RAW_CAREERS[3],
    title: t("j4Title"),
    location: t("j4Location"),
    type: t("fullTime"),
    description: t("j4Desc"),
    requirements: [
      t("j4Req1"),
      t("j4Req2"),
      t("j4Req3"),
      t("j4Req4"),
      t("j4Req5"),
      t("j4Req6"),
      t("j4Req7"),
      t("j4Req8"),
      t("j4Req9"),
    ],
    bonusSkills: [
      t("j4Bonus1"),
      t("j4Bonus2"),
      t("j4Bonus3"),
      t("j4Bonus4"),
      t("j4Bonus5"),
      t("j4Bonus6"),
    ],
    benefits: [
      t("j4Benefit1"),
      t("j4Benefit2"),
      t("j4Benefit3"),
      t("j4Benefit4"),
      t("j4Benefit5"),
    ],
  },
  {
    ...RAW_CAREERS[4],
    title: t("j5Title"),
    location: t("j5Location"),
    type: t("fullTime"),
    description: t("j5Desc"),
    requirements: [
      t("j5Req1"),
      t("j5Req2"),
      t("j5Req3"),
      t("j5Req4"),
      t("j5Req5"),
      t("j5Req6"),
      t("j5Req7"),
      t("j5Req8"),
      t("j5Req9"),
    ],
    bonusSkills: [
      t("j5Bonus1"),
      t("j5Bonus2"),
      t("j5Bonus3"),
      t("j5Bonus4"),
      t("j5Bonus5"),
      t("j5Bonus6"),
    ],
    benefits: [
      t("j5Benefit1"),
      t("j5Benefit2"),
      t("j5Benefit3"),
      t("j5Benefit4"),
      t("j5Benefit5"),
    ],
  },
  {
    ...RAW_CAREERS[5],
    title: t("j6Title"),
    location: t("j6Location"),
    type: t("fullTime"),
    description: t("j6Desc"),
    requirements: [
      t("j6Req1"),
      t("j6Req2"),
      t("j6Req3"),
      t("j6Req4"),
      t("j6Req5"),
      t("j6Req6"),
      t("j6Req7"),
      t("j6Req8"),
      t("j6Req9"),
    ],
    bonusSkills: [
      t("j6Bonus1"),
      t("j6Bonus2"),
      t("j6Bonus3"),
      t("j6Bonus4"),
      t("j6Bonus5"),
      t("j6Bonus6"),
    ],
    benefits: [
      t("j6Benefit1"),
      t("j6Benefit2"),
      t("j6Benefit3"),
      t("j6Benefit4"),
      t("j6Benefit5"),
    ],
  },
];

export default getCareers;
